const ABI = [
  {
    inputs: [
      { internalType: 'uint256', name: '_workerId', type: 'uint256' },
      { internalType: 'uint256', name: '_price', type: 'uint256' },
    ],
    name: 'addAppointment',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'string', name: '_name', type: 'string' }],
    name: 'addUser',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'string', name: '_name', type: 'string' },
      { internalType: 'string', name: '_category', type: 'string' },
      { internalType: 'string', name: '_description', type: 'string' },
      { internalType: 'string', name: '_pfpUri', type: 'string' },
      { internalType: 'uint256', name: '_price', type: 'uint256' },
      { internalType: 'uint256', name: '_rating', type: 'uint256' },
      { internalType: 'string', name: '_meetingLink', type: 'string' },
      { internalType: 'bool', name: '_availability', type: 'bool' },
    ],
    name: 'addWorker',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'uint256', name: '', type: 'uint256' },
    ],
    name: 'appointmentsForWorker',
    outputs: [
      { internalType: 'uint256', name: 'id', type: 'uint256' },
      { internalType: 'address', name: 'customer', type: 'address' },
      { internalType: 'address', name: 'worker', type: 'address' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'appointmentsId',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_workerAddress', type: 'address' },
    ],
    name: 'changeAvailability',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_id', type: 'uint256' },
      { internalType: 'uint256', name: '_price', type: 'uint256' },
    ],
    name: 'changePrice',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'checkUserExists',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'checkWorkerExists',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_addressWorker', type: 'address' },
    ],
    name: 'getAppointmentForAWorker',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'id', type: 'uint256' },
          { internalType: 'address', name: 'customer', type: 'address' },
          { internalType: 'address', name: 'worker', type: 'address' },
        ],
        internalType: 'struct UrbanClapXHuddle.Appointment[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_id', type: 'uint256' }],
    name: 'getUser',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'id', type: 'uint256' },
          { internalType: 'string', name: 'username', type: 'string' },
          { internalType: 'address', name: 'userWallet', type: 'address' },
        ],
        internalType: 'struct UrbanClapXHuddle.User',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getUsername',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_id', type: 'uint256' }],
    name: 'getWorker',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'id', type: 'uint256' },
          { internalType: 'string', name: 'name', type: 'string' },
          { internalType: 'string', name: 'pfp', type: 'string' },
          { internalType: 'string', name: 'category', type: 'string' },
          { internalType: 'address', name: 'workerWallet', type: 'address' },
          { internalType: 'string', name: 'description', type: 'string' },
          { internalType: 'uint256', name: 'price', type: 'uint256' },
          { internalType: 'uint256', name: 'rating', type: 'uint256' },
          { internalType: 'string', name: 'meetingLink', type: 'string' },
          { internalType: 'bool', name: 'isAvailable', type: 'bool' },
          { internalType: 'uint256', name: 'numberOfRaters', type: 'uint256' },
        ],
        internalType: 'struct UrbanClapXHuddle.Worker',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_workerId', type: 'uint256' }],
    name: 'getWorkerAddress',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_workerAddress', type: 'address' },
    ],
    name: 'getWorkerByAddress',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'id', type: 'uint256' },
          { internalType: 'string', name: 'name', type: 'string' },
          { internalType: 'string', name: 'pfp', type: 'string' },
          { internalType: 'string', name: 'category', type: 'string' },
          { internalType: 'address', name: 'workerWallet', type: 'address' },
          { internalType: 'string', name: 'description', type: 'string' },
          { internalType: 'uint256', name: 'price', type: 'uint256' },
          { internalType: 'uint256', name: 'rating', type: 'uint256' },
          { internalType: 'string', name: 'meetingLink', type: 'string' },
          { internalType: 'bool', name: 'isAvailable', type: 'bool' },
          { internalType: 'uint256', name: 'numberOfRaters', type: 'uint256' },
        ],
        internalType: 'struct UrbanClapXHuddle.Worker',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_id', type: 'uint256' }],
    name: 'getWorkerRating',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_worker', type: 'address' },
      { internalType: 'uint256', name: '_rate', type: 'uint256' },
    ],
    name: 'rateWorker',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'userExistsMap',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'userNames',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'users',
    outputs: [
      { internalType: 'uint256', name: 'id', type: 'uint256' },
      { internalType: 'string', name: 'username', type: 'string' },
      { internalType: 'address', name: 'userWallet', type: 'address' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'usersId',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'workerAddressMap',
    outputs: [
      { internalType: 'uint256', name: 'id', type: 'uint256' },
      { internalType: 'string', name: 'name', type: 'string' },
      { internalType: 'string', name: 'pfp', type: 'string' },
      { internalType: 'string', name: 'category', type: 'string' },
      { internalType: 'address', name: 'workerWallet', type: 'address' },
      { internalType: 'string', name: 'description', type: 'string' },
      { internalType: 'uint256', name: 'price', type: 'uint256' },
      { internalType: 'uint256', name: 'rating', type: 'uint256' },
      { internalType: 'string', name: 'meetingLink', type: 'string' },
      { internalType: 'bool', name: 'isAvailable', type: 'bool' },
      { internalType: 'uint256', name: 'numberOfRaters', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'workerExistsMap',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'workerId',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'workers',
    outputs: [
      { internalType: 'uint256', name: 'id', type: 'uint256' },
      { internalType: 'string', name: 'name', type: 'string' },
      { internalType: 'string', name: 'pfp', type: 'string' },
      { internalType: 'string', name: 'category', type: 'string' },
      { internalType: 'address', name: 'workerWallet', type: 'address' },
      { internalType: 'string', name: 'description', type: 'string' },
      { internalType: 'uint256', name: 'price', type: 'uint256' },
      { internalType: 'uint256', name: 'rating', type: 'uint256' },
      { internalType: 'string', name: 'meetingLink', type: 'string' },
      { internalType: 'bool', name: 'isAvailable', type: 'bool' },
      { internalType: 'uint256', name: 'numberOfRaters', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
]
export default ABI;